version: '3'
services:
  java-app:
    image: java-app
    ports:
      - "8080:8080"
    networks:
      - superhero
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - superhero
networks:
  superhero: